name: rpi-test-platform
channels:
  - conda-forge
  - defaults
  - rpi
dependencies:
  - python=3.6
  - flask=1.1.1
  - pip:
      - RPi.GPIO==0.7.0
      - eventlet==0.25.1
      - flask-socketio==3.3.2
      - tornado==6.0.2
